// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mwdtxftqvzmkscczxijh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13ZHR4ZnRxdnpta3NjY3p4aWpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM1MjYxNDksImV4cCI6MjA5OTEwMjE0OX0.tnAuOQAop51mPFCWLU13XzmQHL5ZGZk4htJ1Dinz4hQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});